import xss from "xss"

/**
 * Sanitizes HTML generated by Shiki while preserving syntax highlighting styles.
 * Uses a strict whitelist approach to prevent XSS vulnerabilities.
 */
export function sanitizeShikiHtml(html: string): string {
  if (!html) return ""

  return xss(html, {
    whiteList: {
      pre: ["class", "style", "tabindex"],
      code: ["class", "style", "dir"],
      span: ["class", "style", "line"],
    },
    stripIgnoreTag: true,
    stripIgnoreTagBody: ["script", "style", "iframe", "object", "embed"],
  })
}
